NODE_COUNT = 0

Vagrant.configure("2") do |config|
  config.vm.define "manager" do |subconfig|
    subconfig.vm.box = "ubuntu/jammy64"
    subconfig.vm.hostname = "Manager"
    subconfig.vm.network "public_network", bridge: "wlp5s0"
    subconfig.vm.synced_folder "/home/alexcastro/Documentos/Aprendendo/AprendendoKubernetes", "/data"
  end
  (1..NODE_COUNT).each do |i|
    config.vm.define "worker#{i}" do |subconfig|
      subconfig.vm.box = "ubuntu/jammy64"
      subconfig.vm.hostname = "worker#{i}"
      subconfig.vm.network "public_network", bridge: "wlp5s0"
      subconfig.vm.synced_folder "/home/alexcastro/Documentos/Aprendendo/AprendendoKubernetes", "/data"
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update && apt-get upgrade -y
    apt install -y cloud-init linux-headers-generic linux-headers-virtual linux-virtual
    curl -fsSL https://get.docker.com | bash
  SHELL
end
