apiVersion: v1
kind: Service
metadata:
  labels:
    app: dia1
  name: dia1
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32222
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dia1
  sessionAffinity: None
  type: NodePort
