apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-file
  labels:
    name: configmap
spec:
  containers:
  - name: busy-configmap
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: meu-configmap-vol
      mountPath: /etc/frutas
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: meu-configmap-vol
    configMap:
      name: cores-frutas