apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
  labels:
    name: configmap
spec:
  containers:
  - name: busy-configmap
    image: busybox
    command:
      - sleep
      - "3600"
    env:
      - name: frutas
        valueFrom:
          configMapKeyRef:
            name: cores-frutas
            key: predileta
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"