apiVersion: v1
kind: Pod
metadata:
  name: test-secret
  namespace: default
  labels:
    name: secret
spec:
  containers:
  - name: pod-secret
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - sleep
      - "3600"
    volumeMounts:
      - mountPath: /tmp/secret
        name: my-volume-secret
  volumes:
    - name: my-volume-secret
      secret:
        secretName: my-secret