apiVersion: v1
kind: PersistentVolume
metadata:
  name: terceiro-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/dados3
    server: 10.0.0.10
    readOnly: false
