apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-v1
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 10
  template:
    metadata:
      labels:
        app: myapp
        version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "32111"
    spec:
      containers:
      - name: myapp
        image: linuxtips/nginx-prometheus-exporter:1.0.0
        env:
        - name: VERSION
          value: "1.0.0"
        ports:
        - containerPort: 80
        - containerPort: 32111