apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set-primeiro
spec:
  replicas: 3
  selector:
    matchLabels:
      system: Dia3
  template:
    metadata:
      labels:
       system: Dia3
    spec:
      containers:
      - name: nginxrs
        image: nginx:1.7.9
        ports:
        - containerPort: 80