apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
    run: nginx
    track: stable
  name: myapp
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: myapp
  ports:
  - nodePort: 32222
    name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - nodePort: 32111
    name: prometheus
    port: 32111
    protocol: TCP
    targetPort: 32111
  sessionAffinity: None
  type: NodePort
