apiVersion: v1
kind: pod
metadata:
  name: meudeploy
spec:
  containers:
  - name: meudeploy
    image: nginx:latest
    resources:
      limits:
        memory: "28Mi"
        cpu: "50m"
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /app
      name: meusegredovol
  volumes:
  - name: meusegredovol
    secret:
      secretName: meusegredo
