apiVersion: v1
kind: pod
metadata:
  name: meudeploy-2
spec:
  containers:
  - name: meudeploy-2
    image: nginx:1.16
    resources:
      limits:
        memory: "28Mi"
        cpu: "50m"
    ports:
    - containerPort: 80
    env:
      - name: CHAVE_SECRETA
        valueFrom:
          secretKeyRef:
            name: meusegredo
            key: chave-secreta
      - name: SEGREDO
        valueFrom:
          secretKeyRef:
            name: meusegredo
            key: segredo