apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: app-ingress
  labels:
    name: app-ingress
spec:
  rules:
  - host: meuk8s.com
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: appsvc1
            port:
              number: 80
      - path: /app2
        pathType: Prefix  
        backend:
          service:
            name: appsvc2
            port:
              number: 80
        