apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    name: nginx-ingress
spec:
  rules:
  - host: meuk8s.com
    http:
      paths:
      - backend:
          serviceName: nginx-ingress
          servicePort: 18080
        patch: /nginx_status